# Generated by Django 6.0.4 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aggregator', models.CharField(max_length=255)),
                ('eta', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('courier_code', models.CharField(max_length=50, unique=True)),
                ('cutoff_time', models.TimeField()),
                ('total_freight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
