# Generated by GitHub Copilot on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="user_id",
            field=models.CharField(db_index=True, default="demo_user", max_length=64),
        ),
        migrations.AddField(
            model_name="courier",
            name="user_id",
            field=models.CharField(db_index=True, default="demo_user", max_length=64),
        ),
        migrations.AddField(
            model_name="courier",
            name="pickup_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courier",
            name="reverse_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courier",
            name="prepaid_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courier",
            name="cod_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courier",
            name="ndd_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courier",
            name="zone",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
